version: '2'

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24

services:
  postgres:
    container_name: funcionario_db
    image: postgres:13
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: postgres
    volumes:
       - ./funcionario_db_volume:/var/lib/postgresql/data
       - ./database_ddl.sql:/docker-entrypoint-initdb.d/database_ddl.sql
    ports:
      - "5432:5432"
    networks:
      vpcbr:
        ipv4_address: 172.20.0.10
    restart: on-failure

volumes:
    funcionario_db_volume: