/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ufes.sistemagestaofuncionario.view;

import com.ufes.sistemagestaofuncionario.presenter.BuscarFuncionarioPresenter;
import com.ufes.sistemagestaofuncionario.presenter.CarregarArquivoPresenter;
import com.ufes.sistemagestaofuncionario.presenter.ManterFuncionarioPresenter;
import javax.swing.JMenuItem;

/**
 *
 * @author b1n
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        setVisible(true);
        this.setLocationRelativeTo(this.getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lbVersao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbQtdFuncionarios = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFuncionario = new javax.swing.JMenu();
        miNovoFuncionario = new javax.swing.JMenuItem();
        miBuscarFuncionario = new javax.swing.JMenuItem();
        miCarregarArquivo = new javax.swing.JMenuItem();
        menuSalario = new javax.swing.JMenu();
        menuFerramentas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbVersao.setText("versao");

        jLabel2.setText("XML");

        jLabel3.setText("Txt");

        lbQtdFuncionarios.setText("qtdFuncionarios");

        jLabel5.setText("Logo");

        menuFuncionario.setText("Funcionário");

        miNovoFuncionario.setText("Incluir");
        miNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovoFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionario.add(miNovoFuncionario);

        miBuscarFuncionario.setText("Buscar");
        miBuscarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBuscarFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionario.add(miBuscarFuncionario);

        miCarregarArquivo.setText("Carregar Arquivo");
        miCarregarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCarregarArquivoActionPerformed(evt);
            }
        });
        menuFuncionario.add(miCarregarArquivo);

        jMenuBar1.add(menuFuncionario);

        menuSalario.setText("Salário");
        jMenuBar1.add(menuSalario);

        menuFerramentas.setText("Ferramentas");
        jMenuBar1.add(menuFerramentas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVersao)
                .addGap(73, 73, 73)
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lbQtdFuncionarios)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVersao)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lbQtdFuncionarios))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovoFuncionarioActionPerformed
        new ManterFuncionarioPresenter();
    }//GEN-LAST:event_miNovoFuncionarioActionPerformed

    private void miBuscarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBuscarFuncionarioActionPerformed
        new BuscarFuncionarioPresenter();
    }//GEN-LAST:event_miBuscarFuncionarioActionPerformed

    private void miCarregarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCarregarArquivoActionPerformed
        new CarregarArquivoPresenter();
    }//GEN-LAST:event_miCarregarArquivoActionPerformed

    public JMenuItem getMiNovoFuncionario() {
        return miNovoFuncionario;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbQtdFuncionarios;
    private javax.swing.JLabel lbVersao;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JMenu menuSalario;
    private javax.swing.JMenuItem miBuscarFuncionario;
    private javax.swing.JMenuItem miCarregarArquivo;
    private javax.swing.JMenuItem miNovoFuncionario;
    // End of variables declaration//GEN-END:variables
}
